import { execFileSync } from 'node:child_process';
import { mkdtempSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const sh = (d, c) => execFileSync('bash', ['-c', c], { cwd: d, encoding: 'utf8' });
const rev = (d, r) => sh(d, `git rev-parse ${r}`).trim();
const d = mkdtempSync(join(tmpdir(), 'i4-'));
sh(d, 'git init -q -b main && git config user.email a@b.c && git config user.name t && git config commit.gpgsign false && echo base>README.md && git add -A && git commit -q -m base');
sh(d, 'echo PAYLOAD_AAA > secret.md && git add -A && git commit -q -m o1'); const O1 = rev(d, 'HEAD');
sh(d, 'echo PAYLOAD_BBB > secret.md && git add -A && git commit -q -m o2'); const O2 = rev(d, 'HEAD');
sh(d, 'printf "*.md -diff\\n" > .gitattributes && git add -A && git commit -q -m attrs');
console.log('--- worktree has .gitattributes at HEAD:', sh(d, 'cat .gitattributes').trim());
console.log('\n=== NAIVE: git diff --binary O1^1 O1 (attribute -diff in effect?) ===');
console.log(sh(d, `git diff --binary ${O1}^1 ${O1}`));
console.log('=== NAIVE: git diff --binary O2^1 O2 ===');
console.log(sh(d, `git diff --binary ${O2}^1 ${O2}`));
console.log('=== check-attr on secret.md at worktree ===');
console.log(sh(d, 'git check-attr diff -- secret.md').trim());
console.log('\n=== HARDENED: core.attributesFile=/dev/null + .git/info/attributes "* diff" ===');
writeFileSync(join(d, '.git', 'info', 'attributes'), '* diff\n');
console.log(sh(d, `git -c core.attributesFile=/dev/null diff --no-textconv --no-ext-diff --no-renames --binary -U3 ${O1}^1 ${O1}`));
rmSync(d, { recursive: true, force: true });
